
### Login
POST https://web-gdss.vercel.app/api/auth/login
Content-Type: application/json

{
    "email":"arham@gmail.com",
    "password":"password2"
}

### Register
POST https://web-gdss.vercel.app/api/auth/register
Content-Type: application/json

{
    "nama":"Adam Fatin",
    "email":"adam@gmail.com",
    "password":"password",
    "peran":"Decision Maker 1"
}

### Logout
POST https://web-gdss.vercel.app/api/auth/logout

### Refresh Access Token
POST https://web-gdss.vercel.app/api/auth/refresh 

### Token
@accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoiNjkxMDljNmE2YTBjN2E1Nzg2ZjRjNjk2IiwibmFtYSI6Ik5hY2hzeWFzIEFyaGFtIE11bXRheiIsImVtYWlsIjoiYXJoYW1AZ21haWwuY29tIiwicGVyYW4iOiJEZWNpc2lvbiBNYWtlciAxIiwidGdsX2JlcmdhYnVuZyI6IjIwMjUtMTEtMDlUMTM6NTE6MzguNTAxWiIsImlhdCI6MTc2Mjc2NzU1OCwiZXhwIjoxNzYyNzcxMTU4fQ.z7TRjZxPkQtehDX-uEcbMM5Xhc2L5P5WKXtiAPUc7ns

### Dashboard
GET https://web-gdss.vercel.app/api/
Authorization: Bearer {{accessToken}}

### Get All Users
GET https://web-gdss.vercel.app/api/user/
Authorization: Bearer {{accessToken}}

### Get User By Id
GET https://web-gdss.vercel.app/api/user/find?id_user=6910cb902e5b13934a3a9b67
Authorization: Bearer {{accessToken}}

### Get Total User
GET https://web-gdss.vercel.app/api/user/total
Authorization: Bearer {{accessToken}}

### Update User By Id   
PUT https://web-gdss.vercel.app/api/user
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id_user":"69109c6a6a0c7a5786f4c696",
    "nama":"Nachsyas Arham Mumtaz",
    "email":"arham@gmail.com",
    "peran":"Decision Maker 1"
}

### Create New User
POST https://web-gdss.vercel.app/api/user
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "nama":"Adam Fatin",
    "email":"adam@gmail.com",
    "password":"password",
    "peran":"Decision Maker 2"
}

### Delete User
DELETE https://web-gdss.vercel.app/api/user?id_user=6910cb372e5b13934a3a9b56
Authorization: Bearer {{accessToken}}

### Update Password
POST https://web-gdss.vercel.app/api/user/password
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id_user":"69109c6a6a0c7a5786f4c696",
    "password":"password2"
}

### Get All Alternatif
GET https://web-gdss.vercel.app/api/alternatif
Authorization: Bearer {{accessToken}}

### Get Total Alternatif
GET https://web-gdss.vercel.app/api/alternatif/total
Authorization: Bearer {{accessToken}}

### Add Alternatif
POST https://web-gdss.vercel.app/api/alternatif
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "nama":"Mie Titi Panakkukang",
    "deskripsi":"Mie kering khas Makassar favorit wisatawan."
}

### Update Alternatif
PUT https://web-gdss.vercel.app/api/alternatif
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id_alternatif":"69117a7691a69d09370572a1",
    "nama":"Sop Saudara Irian",
    "deskripsi":"Menyajikan sop khas Makassar dengan cita rasa gurih."
}

### Delete Alternatif
DELETE https://web-gdss.vercel.app/api/alternatif
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id_alternatif":"691180fb65de5d03ecbd1f40"
}

### Get All Kriteria
GET https://web-gdss.vercel.app/api/kriteria
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### Get Kriteria By Id
GET https://web-gdss.vercel.app/api/kriteria/id/691185a10957d42373ba59a5
Authorization: Bearer {{accessToken}}

### Get Kriteria By Tipe
GET https://web-gdss.vercel.app/api/kriteria/tipe/benefit
Authorization: Bearer {{accessToken}}

### Get Total Kriteria
GET https://web-gdss.vercel.app/api/kriteria/total
Authorization: Bearer {{accessToken}}

### Add Kriteria
POST https://web-gdss.vercel.app/api/kriteria
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "nama":"Biaya Transportasi",
    "tipe":"Cost",
    "bobot":3.50,
    "nilai":[
        {"key":"1","value":"Sangat Murah"},
        {"key":"2","value":"Murah"},
        {"key":"3","value":"Cukup Murah"},
        {"key":"4","value":"Mahal"},
        {"key":"5","value":"Sangat Mahal"}
    ]
}

### Update Kriteria
PUT https://web-gdss.vercel.app/api/kriteria
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id_kriteria":"6911858d0957d42373ba59a2",
    "nama":"Kebersihan Tempat",
    "tipe":"Benefit",
    "bobot":4.50
}

### Delete Kriteria
DELETE https://web-gdss.vercel.app/api/kriteria?id_kriteria=69118fb7812b6cf3718a6d7a
Authorization: Bearer {{accessToken}}